version: 2

jobs:
  python2-test:
    docker:
      - image: "python:2.7-stretch"
    steps:
      - checkout
      - run: pip install -e .[all] .[test]
      - run: py.test test/
      - run: pylint pyls test
      - run: pycodestyle pyls test
      - run: pyflakes pyls test

  python3-test:
    docker:
      - image: "python:3.4-stretch"
    steps:
      - checkout
      - run: pip install -e .[all] .[test]
      - run: py.test test/

  lint:
    docker:
    - image: "python:2.7-stretch"
    steps:
    - checkout
    - run: pip install -e .[all] .[test]
    - run: pylint pyls test
    - run: pycodestyle pyls test
    - run: pyflakes pyls test

  publish:
    docker:
      - image: "python:3.4-stretch"
    steps:
      - attach_workspace: { at: . }

workflows:
  version: 2
  build:
    jobs:
      - python2-test
      - python3-test
      - publish:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+((-(beta|rc)[0-9]{1,2})(\.[0-9])?)?/
          requires:
            - python2-test
            - python3-test
